[package]
name = "remotefs-webdav"
version = "0.2.2"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-webdav"
edition = "2024"
homepage = "https://github.com/remotefs-rs/remotefs-rs-webdav"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "webdav", "webdav-client", "rfc4918"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-webdav"
rust-version = "1.94.1"
description = "remotefs WebDAV client library"

[features]
default = ["find"]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
# tests
with-containers = []

[dependencies]
bytes = "1.5"
dav-xml = "0.2"
dav-xml-client = { version = "0.2", default-features = false, features = ["native-tls", "ureq"] }
log = "0.4"
remotefs = "0.3"
thiserror = "2"

[dev-dependencies]
env_logger = "0.11"
pretty_assertions = "1"
serial_test = "4"
uuid = { version = "1", features = ["v4"] }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
