[package]
name = "remotefs-webdav"
version = "0.2.0"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-webdav"
edition = "2024"
homepage = "https://github.com/remotefs-rs/remotefs-rs-webdav"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "webdav", "webdav-client", "rfc4918"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-webdav"
rust-version = "1.94.1"
description = "remotefs WebDAV client library"

[features]
default = ["find"]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
# tests
with-containers = []

[dependencies]
bytes = "1.5"
log = "0.4"
remotefs = "0.3"
reqwest = { version = "0.13", features = ["blocking"] }
thiserror = "2"

# vendored `webdav-xml` dependencies
bytestring = "1.3"
http = "1"
httpdate = "1"
indexmap = "2.2"
mime = "0.3"
nonempty = "0.12"
quick-xml = "0.42"
time = { version = "0.3.34", features = ["formatting", "parsing"] }

[dev-dependencies]
env_logger = "0.11"
pretty_assertions = "1"
serial_test = "4"
uuid = { version = "1", features = ["v4"] }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
